### ISSUE TITLE
Everyone allowed when using Ruby 2.0

### ISSUE THREAD

**Issue by Rockfordal** [stffn/declarative_authorization#173] opened 2013-03-05 17:59 UTC
This is my first time issuing a request, and i apologize for nog being very specific  and not attaching tests, but i thought this was quite important to wave a flag.

ruby 2.0.0p0
rails (3.2.12)
declarative_authorization (0.5.6)
devise (2.2.3)

platform: osx, linux
environments: development, staging

Whuups, i think you can CLOSE this issue unless i already screwed up for deletion :)
this seems to solve my issue in cucumber+manual test:
  -gem 'declarative_authorization', '0.5.6'
 +gem 'declarative_authorization', github: 'stffn/declarative_authorization'

**Comment by stffn** [comment] 2013-03-10 13:07
Duplicate of #160 – I'll push an update

**Closed as completed by stffn** 2013-03-10 13:07 UTC

**Comment by badrah** [comment] 2013-10-10 14:12
I'm sorry, but I don't get it .. What have fixed the issue for you @Rockfordal ?
I've used the newer version 0.5.7 but still everyone is allowed access.

**Comment by Rockfordal** [comment] 2013-10-11 23:31
i did a simple test now just to check.
after changing to 0.5.6 and getting to /users as nonadmin
i switched back to 0.5.7 and was was blocked

ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]  and rails 4.0.0
i can send you my Gemfile if you like

**Comment by badrah** [comment] 2013-10-11 23:58
Thanks Rockfordal!
Something is definitely wrong on my side .. Everyone is still allowed!
I'm using:
0.5.7, ruby 
Ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
Rails 3.2.12
