### ISSUE TITLE
Disable authorization rules in browser

### ISSUE THREAD

**Issue by Odaeus** [stffn/declarative_authorization#116] opened 2011-10-21 00:19 UTC
Hi,

I just installed the Resque gem and when starting up a worker in development with `QUEUE=* rake environment resque:work` I get an exception due to it calling Rails' eager preloading which loads Rails engines:

```
Authorization::DevelopmentSupport::Analyzer requires ruby_parser gem
/home/andrew/.rvm/gems/ruby-1.9.3-rc1/gems/declarative_authorization-0.5.3/lib/declarative_authorization/development_support/analyzer.rb:9:in `rescue in <top (required)>'
```

The relevant engine files have a condition check for  `Authorization::activate_authorization_rules_browser?` to stop them loading when needed but this only checks if the current Rails environment is development.

Is there a way to disable this permanently? Adding the ruby_parser gem slows down my application boot by over a second and I don't use the rules browser.

I guess a reasonable solution would be to override the `activate_authorization_rules_browser?` value in an initializer with a class variable. I would be able to submit a patch for that.

Thanks!
Andrew

**Comment by stffn** [comment] 2011-10-25 11:40
Shouldn't it be possible to override activate_authorization_rules_browser? without a patch?

Generally, a patch would be very much welcome that would begin to better organize the configuration options and make them accessible in the initializer.  Compare #44

**Comment by jobster** [comment] 2012-02-21 20:19
I have this issue as well.  @Odaeus did you find a solution that worked for you?  I don't necessarily need a patch to the declarative_authorization gem, but I do want resque to work in development.  Or, @stffn if you have a better solution, I'd love to hear it.....

I'd rather not install an extra gem just for my development environment as @Odaeus mentioned, so right now, I'm simply going to override `Authorization::activate_authorization_rules_browser?` in a config/initializer as suggested.

This really should be fixed, it shows up other places and in other issues as well.  A search for "ruby_parser gem" returns the following link as the SECOND result:
https://github.com/voormedia/rails-erd/issues/10

**Comment by Odaeus** [comment] 2012-02-21 21:56
I'm afraid I didn't get round to a patch on that. I put ruby_parser in the development group of my Gemfile.

**Comment by jobster** [comment] 2012-02-22 09:51
Here's what I ended up doing.  I put the following code in an initializer:

``` ruby
# config/initializers/declarative_authorization_fix.rb
ALLOW_ROLE_TESTING = false

module Authorization
  def self.activate_authorization_rules_browser?
    ALLOW_ROLE_TESTING and Rails.env.development?
  end
end
```

This way if you do want to turn the default behavior back on, you can just change the value of the `ALLOW_ROLE_TESTING` constant (I know it's a weird name, but I think that's kind of what the "authorization rules browser" gives you: a way to test your roles).

Of course, it's a hack altogether to have to include this initializer file, but I feel that it's better than being forced to include the ruby_parser gem and load all of the extra declarative_authorization routes when they're not needed.  At least it's a working solution until an official fix comes out.

**Comment by stffn** [comment] 2012-03-05 21:33
I think, we can consider this issue a duplicate of #44

**Closed as completed by stffn** 2012-03-05 21:33 UTC
